name = "url-shortener"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-06-21"

[assets]
directory = ".svelte-kit/cloudflare/_app"
binding = "ASSETS"
run_worker_first = true

[[env.production.kv_namespaces]]
binding = "URL_SHORTENER"
id = "c63f222733454633b53b465f96a0bbd9"

[[env.preview.kv_namespaces]]
binding = "URL_SHORTENER"
id = "test"
