name = "url-shortener"
compatibility_date = "2025-06-21"

main = ".svelte-kit/cloudflare/worker.mjs"

# Production KV namespace binding
[[env.production.kv_namespaces]]
binding = "URL_SHORTENER"
id = "c63f222733454633b53b465f96a0bbd9"

# Preview KV namespace binding
[[env.preview.kv_namespaces]]
binding = "URL_SHORTENER"
id = "test"
